### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [ggez/game-template#2]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by icefoxen** [comment]
This is really just a sub-part of the main ggez project: https://github.com/ggez/ggez/

That project does have a logo and so far we're pretty happy with it, so I am not sure we need anything new.  Thank you for the offer though!
